version: "3"
services:
    nextjs:
        build:
            context: .
            dockerfile: ./dockerfiles/nextjs.dev.dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app
        environment:
            - MONGO_URL=mongodb://mongodb:27017/stumble_on
